language: cpp

compiler:
  - gcc

before_script:
    # Install apache's liblog4cc
  - sudo apt-get update -qq
  - sudo apt-get install liblog4cxx10 liblog4cxx10-dev
    # Install more recent version of g++
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - g++ --version
    # Install some boost libraries
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get -qq update
  - sudo apt-get install libboost-regex1.54-dev libboost-filesystem1.54-dev libboost-program-options1.54-dev
    # Install more recent version of ROOT with source
  - wget http://root.cern.ch/download/root_v5.34.30.source.tar.gz -P /tmp/
  - tar -xzf /tmp/root_v5.34.30.source.tar.gz
  - mv root root-src
  - wget http://root.cern.ch/download/root_v5.34.30.Linux-ubuntu12-x86_64-gcc4.6.tar.gz -P /tmp/
  - tar -xzf /tmp/root_v5.34.30.Linux-ubuntu12-x86_64-gcc4.6.tar.gz
  - source ./root/bin/thisroot.sh
  - root-config --libs
  - root-config --cflags
    # Move some header files to common include directory
  - rsync -auv root-src/math/mathmore/inc/Math root/include/

branch:
  only:
    - master

script:
  - mkdir build/ && cd build/ && pwd
  - cmake -D CMAKE_INSTALL_PREFIX=./ -D CMAKE_BUILD_TYPE=Release ../
  - make -j4 && make install && make clean
  - ls -la ./ && ls -la lib/ && ls -la bin/ && ls -la inc/
  - export PATH=$PATH:./bin
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./lib
  - ./bin/stiscan --help
  - ./bin/stihify --help
