sudo: false
language: cpp

compiler:
  - gcc

# Make sure cmake picks up the compiler we want
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kubuntu-backports
    packages:
      - g++-4.8
      - cmake
      - libboost-dev
      - libboost-algorithm-dev

git:
  depth: 1
  submodules: false

before_install:
  - git submodule update --init

before_script:
  - wget http://root.cern.ch/download/root_v5.34.30.source.tar.gz -P /tmp/
  - tar -xzf /tmp/root_v5.34.30.source.tar.gz
  - mv root root-src
  - wget http://root.cern.ch/download/root_v5.34.30.Linux-ubuntu12-x86_64-gcc4.6.tar.gz -P /tmp/
  - tar -xzf /tmp/root_v5.34.30.Linux-ubuntu12-x86_64-gcc4.6.tar.gz
  - source ./root/bin/thisroot.sh
  - root-config --libs
  - root-config --cflags
    # Move some ROOT header files to common include directory
  - rsync -auv root-src/math/mathmore/inc/Math root/include/

branch:
  only:
    - master

script:
  - mkdir build/ && cd build/
  - pwd
  - cmake -D CMAKE_INSTALL_PREFIX=./ ../
  - make -j4
  - make install
  - pwd && ls -la . && pwd && ls -la lib/
