sudo: false

language: cpp
compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kubuntu-backports
    packages:
      - g++-4.8
      - cmake
      - libboost-dev
      - libboost-algorithm-dev

git:
  depth: 1
  submodules: false
before_install:
  - git submodule update --init
before_script:
  - g++ --version
  - cmake --version
  - wget http://root.cern.ch/download/root_v5.34.30.source.tar.gz -P /tmp/
  - tar -xzf /tmp/root_v5.34.30.source.tar.gz
  - mv root root-src
  - wget http://root.cern.ch/download/root_v5.34.30.Linux-ubuntu12-x86_64-gcc4.6.tar.gz -P /tmp/
  - tar -xzf /tmp/root_v5.34.30.Linux-ubuntu12-x86_64-gcc4.6.tar.gz
  - source ./root/bin/thisroot.sh
  - root-config --libs
  - root-config --cflags
  - rsync -auv root-src/math/mathmore/inc/Math root/include/
branch:
  only:
    - master
script:
  - mkdir build/ && cd build/
  - pwd
  - cmake ../
  - make -j4
  - ls -la
